###  DOCKER COMPOSE ###
version: "3"

networks:
  nginx-php80-postgres13-redis:

services:
  ## nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php80-service
      - postgres13-service
    networks:
      - nginx-php80-postgres13-redis

  ## php80
  php80-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php80-container
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php80-postgres13-redis

  #postgres13
  postgres13-service:
    image: postgres:latest
    container_name: postgres13-container
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - nginx-php80-postgres13-redis

  #redis
  redis-service:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - nginx-php80-postgres13-redis
